import "./globals.css";
import { Inter } from "next/font/google";
import { FormProviderPa }  from "@/app/components/Otp/Doctor/FormContextPa";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout2({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <FormProviderPa>
        {children}
       </FormProviderPa>
      </body>
    </html>
  );
}
