//import "./globals.css";
import { Inter } from "next/font/google";
import { FormProviderPh }  from "@/app/components/Otp/Pharmacy/FormContextPh";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout3({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <FormProviderPh>
        {children}
       </FormProviderPh>
      </body>
    </html>
  );
}
